language: node_js
node_js:
  - node

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in travis_key.enc -out travis_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_key
  - ssh-add travis_key

install:
  - npm install
  - npm run deps

script:
  - npm run client-test
  - npm run build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $DOCKER_REPO:$CONTAINER_FE ./client
  - docker push $DOCKER_REPO
  - ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST "(docker stop $CONTAINER_FE || true) && (docker rm $CONTAINER_FE || true)"
  - ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST docker pull $DOCKER_REPO:$CONTAINER_FE
  - ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST docker run -d -p 80:80 --name $CONTAINER_FE -v "/home/nginx/":"/etc/nginx/conf.d" $DOCKER_REPO:$CONTAINER_FE
